console.log(arguments.callee.toString())
console.log(module)
console.log(__filename)
console.log(__dirname)
console.log(exports)
console.log(module.exports)
console.log(module.exports === exports)
console.log(require)
